### ISSUE TITLE
Shared framework schemes issue

### ISSUE THREAD

**Issue by gogisha** [qualaroo/iOSMobileSDK#22]
When trying to add the Qualaroo SDK to my project through Carthage, while I'm able to get the files themselves downloaded and added to my Frameworks paths, there's an error I keep getting when calling `carthage update` :

Dependency "iOSMobileSDK" has no shared framework schemes

After some searching it seems like this might be an issue with the SDK itself somehow, though I am happy to be proven wrong.

**Comment by Aleks9bit** [comment]
fixed
